# 2D `Numpy` in Python
- About using 2D `Numpy` in the Python Programming Language.

## Table of Contents
- Create a 2D Numpy Array
- Accessing different elements of a Numpy Array
- Basic Operations



- Read: **20 min**

## Create a 2D Numpy Array

In [2]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [3]:
# create a list
sample_list = [
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
]
sample_list

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [25]:
# Convert list to the numpy array by casting
# Every element in the list need to be of same data type

array_from_list = np.array(sample_list)
array_from_list

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Let's use **ndim** to obtain the number of dimension 

In [5]:
# show the numpy array dimension
array_from_list.ndim

2

**shape** returns a tuple corresponding to the size or number of each dimension

In [6]:
# Show the numpy array shape

array_from_list.shape

(3, 3)

**size** gives the total number of element in the array

In [7]:
# Show the numpy array size

array_from_list.size

9

## Accessing different elements of a Numpy Array

**Pictorial Explanation:**  
![accessing element](https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFT.png)

We simply use the square brackets and the indices corresponding to the element we would like:

In [8]:
# Access the element on the second row and third column

array_from_list[1, 2]

23

We can also use the following notation to obtain the elements: 

In [9]:
# Access the element on the second row and third column

array_from_list[1][2]

23

**slicing in Numpy array**  
![Slicing array](https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFSF.png)

`Here we would like to obtain first two columns in the first row`

In [10]:
# accessing first two columns in the first row
print("accessing first two columns in the first row: ", array_from_list[0, 0:2])

accessing first two columns in the first row:  [11 12]


In [11]:
# similarly accessing the element on the first and second rows and third columns
print("accessing the element on the first and second rows and third columns", array_from_list[1:3, 2])

accessing the element on the first and second rows and third columns [23 33]


`Process Demonstration:`

![Process Demonstration](https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoTST.png)

## Basic Operations
- **Addition**
- **Multiplication**

## Addition:

![addition process](https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoAdd.png)

In [12]:
# Create numpy array x
X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [13]:
# Create a numpy array Y
Y = np.array([[2, 1], [1, 2]])
Y


array([[2, 1],
       [1, 2]])

Adding two numpy arrays as follows:

In [14]:
# Add X and Y

Z = X+Y
Z

array([[3, 1],
       [1, 3]])

### Multiplication:
- Multiplying numpy array by scaler is similar to multiplying a matrix by scaler


![multiplication](https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoDb.png)

In [15]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [16]:
# Multiply Y with 2
Z = 2 * Y
print("Multiply Y with 2:\n", Z)

Multiply Y with 2:
 [[4 2]
 [2 4]]


- Multiplication of two arrays corresponds to an **element-wise product or Hadamard product**
- The **Hadamard product** corresponds to multiplying each each of the elements in the same position.
- **Pictorial Explanation:**
![element wise product](https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoMul.png)

In [17]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [18]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [19]:
# Multiply X with Y

Z = X * Y
print(f"The element wise product between two numpy arrays X and Y is:\n {Z}")

The element wise product between two numpy arrays X and Y is:
 [[2 0]
 [0 2]]


`Matrix Multiplication: Dot Product`

In [20]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [21]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

We use the numpy function **dot** to multiply the arrays together

In [22]:
# Calculate the dot product
Z = np.dot(A,B)
print(f"The dot product between two numpy arrays is:\n{Z}")

The dot product between two numpy arrays is:
[[0 2]
 [0 2]]


**Transpose:**
- We use the numpy attribute **T** to calculate the transposed of the matrix

In [23]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [24]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])