# `Numpy Array`

## Table of contents
- Numpy Array manipulation
   - Attributes
   - Indexing
   - Slicing
   - Reshaping
   - Joining
   - Splitting
- Find index of all `peaks` in a 1D array
- Subtract a 1D array from the 2D array



- Read: **15 min**

## Numpy Array Manipulation
- **Atributes**
- **Indexing**
- **Slicing**
- **Reshaping**
- **Joining-Splitting**

### Attributes
- **ndarray.ndim:** _Represents the number of dimensions(axes) of the ndarray_
- **ndarray.shape:** _Gives the tuple of integers representing the size of the ndarray in each dimension_
- **ndarray.size:** _Gives the total number of elements in the ndarray. Equals to the product of elements of the result of the attribute **shape**_
- **ndarray.dtype:** _tells the data type of the elements of a Numpy array. In Numpy array, all the elements have the same data type._
- **ndarray.itemsize:** _returns the size(in bytes) of each element of a Numpy array._

First, let's create a numpy array from list to work on and let's see example for each of the **attributes** mention above:

In [2]:
# import 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# create array
sample_array = np.array([[3, 4, 6], [0, 8, 1]])
sample_array

array([[3, 4, 6],
       [0, 8, 1]])

Now, let's understand mentioned **attributes** of numpy array:

In [4]:
# ndarray.ndim
print(f"The dimension of sample array is: {sample_array.ndim}")

The dimension of sample array is: 2


In [5]:
# ndarray.shape
print(f"The shape of sample array is: {sample_array.shape}")

The shape of sample array is: (2, 3)


In [6]:
# ndarray.size
print(f"The total number of elements in the sample array is: {sample_array.size}")

The total number of elements in the sample array is: 6


In [7]:
# ndrray.dtype
print(f"The data type of elements of sample array is: {sample_array.dtype}")

The data type of elements of sample array is: int64


In [8]:
# ndarray.itemsize, returns the size (in bytes) of each element of a Numpy array
print(f"The size of each element in the numpy array is: {sample_array.itemsize}")

The size of each element in the numpy array is: 8


### Indexing 
- **Introduction**
- **Indexing 1D array**
- **Indexing 2D array**

#### Introduction:
- Array indexing is same as accessing an array element
- Accessing element can take place by referring to its index number
- The indexes in Numpy array starts with 0, meaning that the first element has index 0, and the second has index 1 etc.

#### Indexing 1D array
- Indexing 1D array means accessing element via 1D array
- **Pictorial Expalanation:**

![image description](https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumOneNp.png)

In [9]:
# create a demo 1D array
one_d_array = np.array([0, 1, 2, 3, 4])

# print each element
print("a[0]: ", one_d_array[0])
print("a[1]: ", one_d_array[1])
print("a[2]: ", one_d_array[2])
print("a[3]: ", one_d_array[3])

a[0]:  0
a[1]:  1
a[2]:  2
a[3]:  3


### Indexing 2D array
- Indexing 2D array is same to the accessing element via 2D array
- We use rectangular bracket to access the different elements via 2D array
- **Pictorial Representation:**

![Indexing 2D array](https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFT.png)

In [9]:
# create 2D array

a = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

# Access the element on the second row and third column

print(f"Accessing the element on the second row and third column: {a[1, 2]}")
print(f"Accessing the element on the third row and third column: {a[2][2]}")

Accessing the element on the second row and third column: 23
Accessing the element on the third row and third column: 33


### Slicing  
- **Introduction**
- **Slicing 1D array**
- **Slicing 2D array**

#### Introduction:
- Slicing in python means taking elements from one given index to another given index.
- Like lists, we can slice the numpy array
- We pass slice instead of index like this: **[start:end].**
- We can also define the step like this: **[start:end].**
- If we don't pass start its considered 0
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered 1

#### Slicing 1D array
`Q. Slice elements from index 1 to index 5 from the following array`

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(f"Slicing from index 1 to 5: {arr[1:5]}")

Slicing from index 1 to 5: [2 3 4 5]


**Note:** The result _includes_ the start index, but excludes the end index

`<code>Q. Slice elements from index 4 to the end of the array:`

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(f"Slicing from index 4 to the end of the array is: {arr[4:]}")

Slicing from index 4 to the end of the array is: [5 6 7]


`Q. Slice elements from the beginning to index 4 (not included)`

In [77]:
print(f"Slicing element from begining to index 4 (not included): {arr[:4]}")

Slicing element from begining to index 4 (not included): [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


`Negative Slicing:` _use the minus operator to refer to an index from the end_  
`Q. Slice from the index 3 from the end to index 1 from the end`

In [13]:
print(f"Slice from the index 3 from the end to index 1 from the end: {arr[-3:-1]}")

Slice from the index 3 from the end to index 1 from the end: [5 6]


`**STEP:**` use the **step** value to determine the step of the slicing  

`Q. Use the step value to determine the step of slicing`

In [14]:
print(f"Slicing array from index 1 to index 5 with the step of 2: {arr[1:5:2]}")

Slicing array from index 1 to index 5 with the step of 2: [2 4]


`Q. return every element from numpy array with step 2.`

In [15]:
print(f"Every element from numpy array with the step: {arr[::2]}")

Every element from numpy array with the step: [1 3 5 7]


#### Slicing 2D array
- `Pictorial Representation`

![Slicing 2D array](https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFSF.png)

`Here we would like to obtain first two columns in the first row`

In [16]:
# create 2D array

# create a list
sample_list = [
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
]

array_from_list = np.array(sample_list)
array_from_list

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [17]:
# accessing first two columns in the first row
print("accessing first two columns in the first row: ", array_from_list[0, 0:2])

accessing first two columns in the first row:  [11 12]


In [18]:
# similarly accessing the element on the first and second rows and third columns
print("accessing the element on the first and second rows and third columns", array_from_list[1:3, 2])

accessing the element on the first and second rows and third columns [23 33]


`Process Demonstration:`  
![Slicing Process Demonstration](https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoTST.png)

### Reshaping

- _**Introduction**_
- _**Reshape From 1D to 2D**_
- _**Reshape From 1D to 3D**_
- _**Can We Reshape Into any Shape**_
- _**Flattening the arrays**_
- _**Ravel()**_
- _**Difference between Flatten() and Ravel()**_

#### Introduction
- Reshaping means changing the shape of an array
- The shape of an array is the number of elements in each dimension
- By reshaping we can add or remove dimensions or change the number of elements in each dimension

#### Reshape From 1D to 2D

`Q. Convert the following 1D array with 12 elements into a 2D array`

In [19]:
# create a array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_arr = arr.reshape(4, 3)

print(f"array before reshaping:\n {arr}")

print(f"\narray after reshaping to shape (4, 3):\n {new_arr}")

array before reshaping:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

array after reshaping to shape (4, 3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


As we can see outermost dimension has 4 arrays, each with 3 elements

### Reshape From 1D to 3D
- to give shape factor 1D length by 2
- `Q. Covert the following 1D array with 12 elements into a 3D array`

In [20]:
# sample array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# reshape to 3D array
new_arr = arr.reshape(2, 3, 2)

print(f"array before reshaping to 3D is:\n {arr}")

print(f"\narray after reshaping to 3D is:\n {new_arr}")

array before reshaping to 3D is:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

array after reshaping to 3D is:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### Can We Reshape Into any Shape
- **Yes**, as long as the elements required for reshaping are equal in both shapes
- `Q. Try Converting 1D array with 8 elements to a 2D array with 3 elements in each dimension`

- `Note:` This process will raise an exception as there are 8 elements in 1D and 9 elements in 2D after reshaping

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# reshape to 3x3
newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

As we can see this lead to an exception as expected

#### Flattening The Arrays
- Flattening the array means converting multidimensional array into a 1D array.
- We can use `reshape(-1)` to do this.

- `Q. Convert the array into a 1D array`

In [22]:
# create sample array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the array
new_arr = arr.reshape(-1)

print(f"Array before flattening:\n{arr}")
print(f"\nArray after flattening:\n{new_arr}")

Array before flattening:
[[1 2 3]
 [4 5 6]]

Array after flattening:
[1 2 3 4 5 6]


#### Ravel()
- returns contiguous flattened array(1D array with all the input-array elements and with the same type as it)
- A copy is made only if needed

In [23]:
# ravel
print(f"ravel array: {arr.ravel()}")

ravel array: [1 2 3 4 5 6]


#### Difference between Flatten() and Ravel()
- `Ravel()`
    - Returns only reference/view of origin
    - If you modify the array you would notice that the value of original array also changes
    - Ravel is faster than flatten() as it does not occupy any memory
    - Ravel is a library-level function i.e. we can use **np.ravel(a, order="c")**
        
- `Flatten()`
    - Return copy of original array.
    - If you modify any value of this array value of original array is not affected.
    - Flatten() is comparatively slower than ravel() as it occupies memory.
    - Flatten is a method of an ndarray object, i.e. **ndarray.flatten(a)**. We can't use  **np.flatten()**

In [24]:
# Python code to differentiate between flatten and ravel in numpy

# create a numpy array
a = np.array([[1, 2, 3, 4], [3, 1, 4, 2]])

# print the array a
print(f"Original array: \n{a}")

# check dimension of array
print("\nDimension of array: ", (a.ndim))

print("\n***Output for RAVEL*** \n")
# convert nd array to 1D array
b = a.ravel()

# Ravel only passes a reference of original array to array 'b'
print(b)
b[0] = 1000
print(b)

# Note here that value of original array 'a' at a[0, 0] also becomes 1000
print(a)

print("\n***Output for FLATTEN***\n")

# convert nd array to 1D array
c = a.flatten()

# Flatten passes a copy of original array to 'c'
print(c)
c[0] = 0
print(c)

# Note now changing the value of c there is no affect on value of original array 'a'
print(a)

Original array: 
[[1 2 3 4]
 [3 1 4 2]]

Dimension of array:  2

***Output for RAVEL*** 

[1 2 3 4 3 1 4 2]
[1000    2    3    4    3    1    4    2]
[[1000    2    3    4]
 [   3    1    4    2]]

***Output for FLATTEN***

[1000    2    3    4    3    1    4    2]
[0 2 3 4 3 1 4 2]
[[1000    2    3    4]
 [   3    1    4    2]]


### Joining  
   - **Introduction**
   - **Joining Arrays Using Stack Functions**
   - **Stacking Along Rows**
   - **Stacking Along Columns**
   - **Stacking Along Height (depth)**

### Introduction
   - Joining means putting content of two or more arrays in a single array.
   - In SQL we join tables based on key, whereas in NumPy we join arrays by axes.
   - we pass sequence of arrays that we want to join to the `concatenate()` function, along with the axes.
   - If axis is not explicitly passed, it is taken as 0.
   - After concatenating Dimensions of resulting array will be same as that of individual array.
   - Order of concatenation will be based on the order in which array are passed to the `concatenate()` function
   - **Example:**

In [2]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# display array
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")

arr = np.concatenate((arr1, arr2))

print(f"Concatenating 1D array: {arr}")

Array 1: [1 2 3]
Array 2: [4 5 6]
Concatenating 1D array: [1 2 3 4 5 6]


`Q.Join two 2-D arrays along rows (axis=1)`

In [4]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### Joining Arrays Using Stack Functions 
   - Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
   - We concatenate two 1D arrays along the second axis which would result in putting them one over the other, i.e. **Stacking**
   - We pass a sequence of arrays that we want to join to the `stack()` method along with the axis.
   - If axis is not explicitly passed it is taken as 0.

In [7]:
arr = np.concatenate((arr1, arr2), axis=1)

print(arr1)
print(arr2)
print(f"Joining Arrays Using Stack Functions: {arr}")

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Joining Arrays Using Stack Functions: [[1 2 5 6]
 [3 4 7 8]]


#### Stacking Along Rows

Numpy provides a helper function: `hstack()` to stack along rows

In [41]:
stack_along_rows = np.hstack((arr1, arr2))

print(f"Stacking along rows: {stack_along_rows}")

Stacking along rows: [[1 2 5 6]
 [3 4 7 8]]


#### Stacking Along Columns

NumPy provides a helper function: `vstack()` to stack along columns.

In [42]:
stack_along_columns = np.vstack((arr1, arr2))

print(f"Stacking along columns: {stack_along_columns}")

Stacking along columns: [[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Stacking Along Height (depth)
NumPy provides a helper function: `dstack()` to stack along height, which is the same as depth
    
Height stacking increases Array Dimension

In [47]:
stack_along_depth = np.dstack((arr1, arr2))
print(f"Stacking along height:\n {stack_along_depth}")

Stacking along height:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


### Splitting
   - **Introduction**
   - **Splitting 2D Arrays**

#### Introduction
   - Splitting is reverse operation of joining
   - Joining merges multiple arrays into one and Splitting breaks one array into multiple one.
   - We use `array_split()` for splitting arrays.
   - We pass it the array we want to split and the number of splits.
   - **Example:**

In [52]:
# splitting 1D arrays

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = np.array_split(arr, 3)

print(f"array after splitting is: {newarr}")

array after splitting is: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


If the array has less elements than required, then last end array is null

`Q. Split [1, 2, 3, 4, 5, 6] into four parts`

In [8]:
# define array
arr = np.array([1, 2, 3, 4, 5, 6])
print(f"origina array: {arr}")

# split
splitted_arr = np.array_split(arr, 4)
print(f"splitted array using array_split(): {splitted_arr}")

origina array: [1 2 3 4 5 6]
splitted array using array_split(): [array([1, 2]), array([3, 4]), array([5]), array([6])]


**Note:**
`We also have method split() available but it will not adjust elements when elements are less in source array for splitting like in example above`  

`In such case **array_split()** worked properly but **split()** would fail.`

Let's see **split()** gives error 

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])

print("***As Expected split() throws an error:***\n")

split_arr = np.split(arr, 4)

***As Expected split() throws an error:***



ValueError: array split does not result in an equal division

#### Splitting 2D Arrays
- Use the same syntax when splitting 2D arrays
- use `array_split()` method, pass in the array you want to split and the number of split you want to do.

`Q. Split the 2D array into 3 2D arrays`

In [57]:
# Split Example 1
sample_arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

split_sample_arr = np.array_split(sample_arr, 3)

print(f"Splitting 2D array into 3 2D array:\n {split_sample_arr}")

Splitting 2D array into 3 2D array:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [58]:
# Split Example 2
sample_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# split into 3 sub 2D arrays
split_sample_arr = np.array_split(sample_arr, 3)

print(f"Splitting 2D array into 3 2D array:\n {split_sample_arr}")

Splitting 2D array into 3 2D array:
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


- In addition you can specify which axis you want to do the split around
- The example below also returns three 2D arrays, but they are split along the row(axis=1)

In [78]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15]])]


An alternate solution is using `hsplit()` opposite of `hstack()`

In [74]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr_hsplit = np.hsplit(arr, 3)
newarr_vsplit = np.vsplit(arr, 3)
print(f"hsplit:\n {newarr_hsplit}")

print(f"vsplit:\n {newarr_vsplit}")

hsplit:
 [array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
vsplit:
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


Also, <strong>dsplit()</strong> is alternate to dstack().<br>
<strong>dsplit()</strong> only works for array of 3 or more dimension

## Find index of all **peaks** in a 1D array
- Here peaks are point surrounded by small value
- A array element is <code>peak</code> if it is not smaller than its neighbour values
- **Example:**
    - **Inputs:** array[] = {10, 20, 15, 2, 23, 90, 67}
    - **Outputs: </strong> 20 or 90
    - The element 20 has neighbours 10 and 15, both of them are less than 20, Similarly 90 has neighbours 23 and 67.
    
- **Note:**
   - If the input array is sorted in ascending order, the last element is always a peak element.
   - If the input array is sorted in descending order, the first element is always a peak element.
   - If all elements of input array are same, every element is a peak element.
    
- **Naive Approach:** The array can be traversed and the element whose neighbours are less than that element can be noted.
   - **Algorithm:**
      - If in the array, the first element is greater than the second or the last element is greater than the second last, then those are the peak element, so note index       
      - For others peak element, traverse the array from the second index to the second last index   
      - If for an element array[i], it is greater than both its neighbour, i.e., array[i]>array[i-1] and array[i]>array[i+1], then note the index of that element.    

In [95]:
# arr = np.array([1, 2, 3, 4, 5, 6])

def find_peak_index_in_array(sample_array):  
    """
    finds and returns the list of index of all the peak elements in the sample array(1D) passed as an arguments using 
    naive approach
    
    Arguments:
    sample_array: sample array from which index of peak elements to be extracted
    
    Returns:
    peak_index_list: List containing index of all the peak elements in sample array
    """
    arr_len = sample_array.shape[0]
    peak_index_list = []

    # extract peak index if peak element is first and last element of array
    if sample_array[0]>sample_array[1]:
        peak_index_list.append(0)
    elif sample_array[arr_len-1]>sample_array[arr_len-2]:
        peak_index_list.append(arr_len-1)

    for index in range(1, arr_len-1):
        if (sample_array[index]>=sample_array[index-1] and sample_array[index]>=sample_array[index+1]):
            peak_index_list.append(index)
    return peak_index_list

sample_array = np.array([10, 20, 15, 2, 23, 90, 67])

peak_index_list = find_peak_index_in_array(sample_array)

print(f"List of all the index of peak elements in array {sample_array} is\are:\n {peak_index_list}")

List of all the index of peak elements in array [10 20 15  2 23 90 67] isre:
 [1, 5]


**Complexity Analysis:**
   - **Time Complexity:**O(n)
      - One traversal is needed through entire 1D array, so the time complexity is O(n)
     
   - **Space Complexity:**O(1)
      - No extra space is needed in the process of obtaining answer, so space complexity is constant
     
    
`Visit for more about complexity:`[Complexity Analysis](https://medium.com/@whosale/understanding-time-and-space-complexity-f94b3140541b)

- **Divide and Conquer**
   - `Divide and Conquer` can be used to find the peak in **O(Logn)** time  
   - The idea is based on the technique of binary search to check if the middle element is the peak element or not.
   - If the middle element is not the peak element, then check, 
   - if the element on the right side is greater than the middle element then there is always a peak element on the right side.
   - If the element on the left side is greater than the middle element then there is always a peak element on the left side.
   - Using recursion, the peak element can be found in **Log n** time.
    


- **Algorithm:**
   - Create two variables, l and r, initialize l=0 and r=n-1
   - Iterate the steps below till l <= r, lowerbound is less than the upperbound
   - Check if the mid value or index mid = (l+r)/2, is the peak element or not, if yes then print the element and terminate
   - Else if the element on the left side of the middle element is greater, then check for peak element on the left side, i.e. update r = mid-1
   - Else if the element on the right side of the middle element is greater, then check for peak element on the right side, i.e. update l = mid+1
    

In [100]:
# A python3 program to find a peak element using divide and conquer strategy
# Define a binary search based function that returns index of a peak element
def find_peak_divide_conquer(arr, low, high, n):
    """
    Returns a peak element from the input array passed as an argument with the technique of divide and conquer 
    recursively (i.e. calling the same function multiple times.)
    
    Arguments:
    arr: sample array, 1D numpy array
    low: index of first element of array
    high: index of last element of array
    n: number of elements in the array, length of 1D array
    
    Return:
    a peak element from an input array
    """
    # Find index of middile element i.e. (low+high)/2
    mid = low+(high-low)/2
    mid = int(mid)
    
    # Compare middle element with its neighbours (if neighbour exists)
    if ((mid == 0 or arr[mid - 1] <= arr[mid]) and (mid == n - 1 or arr[mid + 1] <= arr[mid])): 
        return mid
    # If middle element is not peak and its left neighbour is greater than it, then left half must have a peak
    elif(mid>0 and arr[mid-1]>arr[mid]):
        return find_peak_divide_conquer(array, low, (mid-1), n)
    
    # If middle element is not peak and its right neighbour is greater than it, the right half must have a peak
    else:
        return find_peak_divide_conquer(array, (mid+1), high, n)
    
# Define rapper over recursive function find_peak_divide_conquer()
def find_peak(array, n):
    return find_peak_divide_conquer(array, 0, n-1, n)
# Sample array 
array = np.array([10, 20, 15, 2, 23, 90, 67])
n = array.shape[0]
print("Index of a peak point is: ", find_peak(array, n))

Index of a peak point is:  1


As we can see we have obtained 1st peak point i.e. at index 1: <code>20</code>

**Complexity Analysis:**
   - **Time Complexity:**O(n)
      - Where n is the number of elements in the input array. In each step our search becomes half. So it can be compared to Binary Search. So the time complexity is `O(logn)`
     
   - **Space Complexity:**O(1)
      - No extra space is needed in the process of obtaining answer, so space complexity is constant
     
    
`Visit for more about complexity:`[Complexity Analysis](https://medium.com/@whosale/understanding-time-and-space-complexity-f94b3140541b)

## Subtract a 1D array from the 2D array   

`Q. Subtract 1d array from 2d array such that each item of 1d array subtracts from respective row of 2D array`
   
Before answer to the question, let's understand the concept of **BroadCasting with Numpy Arrays**

#### Broadcasting with NumPy Arrays
   - The term **broadcasting** refers to how numpy treats with different Dimension during arithmetic operations which lead to certain constraints, the smaller array is broadcast to larger array so that they have compatible shapes.
   - Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python as NumPy is implemented in C.
   - It does this without making needless copies of data and which leads to efficient algorithm implementations.
   - There are cases where broadcasting is a bad idea because it leads to inefficient use of memory that slow down the computation.
   - **Example:**
      - Scaling 2D array with 1D array

`Answer: Now let's use this broadcasting concept to answer the above questions`

In [126]:
def subtract_1D_from_2D_array(one_d_array, two_d_array):
    # Reshape 1D array to (one_d_array.shape[0], 1)
    one_d_array = one_d_array.reshape(one_d_array.shape[0], 1)
    
    # Subtract reshaped 1D array from 2D array
    # broadcasting take place to match size to 2D array
    subtract_result = two_d_array-one_d_array
    
    return subtract_result

# Initialize random array
one_d_array = np.array([1, 2, 3])
two_d_array = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Subtraction
subtract_result = subtract_1D_from_2D_array(one_d_array, two_d_array)
print(f" {two_d_array} Minus {one_d_array} \n is: \n{subtract_result}")

 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]] Minus [1 2 3] 
 is: 
[[3 4 5]
 [5 6 7]
 [7 8 9]]
